# Generated by Django 5.0.3 on 2024-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('urgency', models.CharField(max_length=50)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='static/')),
            ],
        ),
    ]
